import streamlit as st
import json
from database import SceneStorage
from chatbot import ChatBot
from dotenv import load_dotenv
import os

load_dotenv(override=True)
api_key = os.getenv("OPENAI_API_KEY")

st.set_page_config(page_title="Scene Monitor Dashboard", page_icon="🛡️")
st.title("🛡️ Scene Monitor Dashboard")

storage = SceneStorage()
chatbot = ChatBot(api_key=api_key)

# --- SIDEBAR CONTROLS ---
st.sidebar.header("Controls")
question = st.sidebar.text_input("Ask a question about the scene logs:")

st.sidebar.markdown("---")
st.sidebar.subheader("Report Generation")

# Button to generate the markdown report
if st.sidebar.button("📝 Generate report.md"):
    logs = storage.query()
    if logs:
        with st.spinner("Analyzing logs and generating report..."):
            # Prompt the chatbot for a formal summary
            report_prompt = "Provide a detailed surveillance report based on these logs. Summarize key events, detected individuals, and any suspicious activities like fighting or weapons."
            report_content = chatbot.ask(report_prompt, logs)

            # Save to report.md
            try:
                with open("report.md", "w", encoding="utf-8") as f:
                    f.write("# 🛡️ Surveillance Analysis Report\n\n")
                    f.write(
                        f"**Generated on:** {os.path.normpath(os.getcwd())}\n\n")
                    f.write("## Executive Summary\n")
                    f.write(report_content)
                    f.write("\n\n---\n*Auto-generated by CamAI Dashboard*")

                st.sidebar.success("✅ report.md saved!")
                st.toast("Report generated successfully!")
            except Exception as e:
                st.sidebar.error(f"Error saving file: {e}")
    else:
        st.sidebar.warning("No logs available to generate a report.")

# --- MAIN CONTENT: LOGS ---
st.subheader("📜 Recent Scene Logs")
logs = storage.query()

if logs:
    # Display the last 10 logs
    for row in logs[-10:]:
        # row structure: (id, timestamp, clip_top3, yolo_detections)
        _, timestamp, clip_top3, yolo_detections = row

        with st.expander(f"🕒 Log entry at {timestamp}"):
            col1, col2 = st.columns(2)
            with col1:
                st.markdown("**CLIP Scene Recognition:**")
                st.write(json.loads(clip_top3))
            with col2:
                st.markdown("**YOLO Object Detection:**")
                st.write(json.loads(yolo_detections))
else:
    st.info("No logs yet. Run your processing script to capture data.")

# --- CHATBOT SECTION ---
if question:
    st.divider()
    st.subheader("🤖 Chatbot Answer")
    with st.chat_message("assistant"):
        answer = chatbot.ask(question, logs)
        st.write(answer)
